# .github/workflows/validate.yml

name: Validate Documents and JSON

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build JAR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'  # ✅ Кэширует зависимости Maven между запусками
      - name: Build with Maven
        run: mvn --batch-mode --show-version clean package
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: validator-jar
          path: target/*-jar-with-dependencies.jar
          retention-days: 1

  validate-docs-servis:
    name: Validate docs-servis
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: validator-jar
          path: target
      - name: Run validation
        run: java -jar target/*-jar-with-dependencies.jar docs-servis

  validate-check-list:
    name: Validate check-list
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: validator-jar
          path: target
      - name: Run validation
        run: java -jar target/*-jar-with-dependencies.jar check-list

  validate-csv:
    name: Validate CSV
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: validator-jar
          path: target
      - name: Run validation
        run: java -jar target/*-jar-with-dependencies.jar csv

  validate-json:
    name: Validate JSON
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: validator-jar
          path: target
      - name: Run validation
        run: java -jar target/*-jar-with-dependencies.jar json